name: DuraBlock
version: '1.0-SNAPSHOT'
main: me.raisy.durablock.DuraBlockPlugin
api-version: '1.21'

depend:
  - DecentHolograms

commands:
  setcustomblock:
    description: "setcustomblock command"
    permission: durablock.commands.setcustomblock
    usage: /setcustomblock <block-type>

  reloadcustomblocks:
    description: "reload command"
    permission: durablock.commands.reload
    usage: /reloadcustomblocks

  listcustomblocks:
    description: "listcustomblock command"
    permission: durablock.commands.listcustomblocks
    usage: /listcustomblocks

  deletecustomblock:
    description: "deletecustomblock command"
    permission: durablock.commands.deletecustomblock
    usage: /deletecustomblock

  durablock:
    description: "DuraBlock command"
    permission: durablock.commands.main
    usage: /durablock
    aliases:
      - durablocks

permissions:
  durablock.commands.setcustomblock:
    description: "Permission for setcustomblock command"
    default: op
  durablock.commands.listcustomblocks:
    description: "permission for listcustomblocks command"
    default: op
  durablock.commands.deletecustomblock:
    description: "Permission for deletecustomblock command"
    default: op
  durablock.commands.reload:
    description: "Permission for reloadcustomblocks command"
    default: op
  durablock.commands.main:
    description: "Permission for durablock command"
    default: op