name: DuraBlock
version: '${project.version}'
main: me.raisy.durablock.DuraBlockPlugin
api-version: '1.19'

depend:
  - DecentHolograms

commands:
  durablock:
    description: "DuraBlock command"
    permission: durablock.commands.main
    usage: /durablock
    aliases:
      - durablocks

permissions:
  durablock.commands.main:
    description: "Permission for durablock command"
    default: op